name: Release
# This workflow is triggered when publishing a GitHub release
on:
  push:

jobs:
  release_docker:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    name: Start Docker release process
    timeout-minutes: 60
    steps:
    - name: get secrets
      id: secrets
      uses: SonarSource/vault-action-wrapper@8e22afd670393ed80f489f5dbd517d09ea21d75b # 2.4.3-1
      with:
        secrets: |
          development/github/token/SonarSource-sonar-scanner-cli-release token | GITHUB_TOKEN_RELEASE;
          development/kv/data/slack token | SLACK_BOT_TOKEN;
    - name: Create Release for Docker Image
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).GITHUB_TOKEN_RELEASE }}
        GITHUB_REPOSITORY: SonarSource/sonar-scanner-cli-docker
      with:
        tag_name: "refs/tags/5.0.0.2966"
        body: Release containing ScannerCLI version 5.0.0.2966
        draft: false
        prerelease: false
    - name: Notify failures on Slack
      uses: slackapi/slack-github-action@v1.23.0
      if: failure()
      with:
        channel-id: team-sonarqube-build
        slack-message: "Release failed, see the logs at https://github.com/={{ GITHUB_REPOSITORY }}/actions by {{ GITHUB_ACTOR }}"
      env:
        SLACK_BOT_TOKEN: ${{ fromJSON(steps.secrets.outputs.vault).SLACK_BOT_TOKEN }}
